title: "Duvan Mendoza Ortega"
description: "Machine Learning Engineer focused on NLP, LLM systems, LoRA fine-tuning, and backend AI infrastructure."
url: "https://duvi-m.github.io"

theme: minima

header_pages:
  - projects.md
  - roadmap.md
  - resources.md
  - about.md

minima:
  skin: classic
  social_links:
    - { platform: github,  user_url: "https://github.com/duvi-m" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/duvan-mendoza-ortega-87bb57321" }

sass:
  style: compressed
